version: 2.1
orbs:
  node: circleci/node@4.7.0
  
jobs:
  test:
    parameters:
      directory:
        type: string
    docker:
      - image: cimg/node:12.22.10
    steps:
      - checkout
      - node/install-packages:
          app-dir: <<parameters.directory>>
          cache-version: <<parameters.directory>>-1
      - run:
          command: npm run ci:test
          name: Run tests
          working_directory: <<parameters.directory>>



workflows:
  on_commit:
    jobs:
      - test:
          name: "Package Tests"
          directory: "package"
      - test:
          name: "Test Runner Tests"
          directory: "test-runner"