version: 2.1
orbs:
  node: circleci/node@4.7.0
  
jobs:
  test:
    parameters:
      directory:
        type: string
    docker:
      - image: cimg/node:12.22.10
    steps:
      - checkout
      - node/install-packages
      - run:
          command: cd <<parameters.directory>>
          name: Run tests
      - run:
          command: npm run test
          name: Run tests


workflows:
  on_commit:
    jobs:
      - test:
          directory: "package"
      - test:
          directory: "test-runner"